apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: smart-devops

  labels:
     app: backend

spec:
  selector:
    app: backend

  ports:
  - name: http
    port: 8081
    targetPort: 8081

  type: ClusterIP